steps:
# Step 0: Clone Repo

- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh


# Step 0: Clone Repo
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'git@github.com:ThomasPolzer/repo-4-kubernetes.git']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Step 1: Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/demo-repo-04/${_CINAME}:${_VERSION}', '.' ]

# Step 2: Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/demo-repo-04/${_CINAME}:${_VERSION}']



substitutions:
  _PROJECT_ID: robotic-shelter-457318-u6
  _CINAME: gke-image
  _VERSION: v1.0

options:
  logging: CLOUD_LOGGING_ONLY


availableSecrets:
  secretManager:
  - versionName: projects/101192578176/secrets/github-ssh-key/versions/latest
    env: 'SSH_KEY'