steps:
# Step 0: Clone Repo
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'git@github.com:ThomasPolzer/repo-4-kubernetes.git']

# Step 1: Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/demo-repo-04/${_CINAME}:${_VERSION}', '.' ]

# Step 2: Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/demo-repo-04/${_CINAME}:${_VERSION}']

substitutions:
  _PROJECT_ID: robotic-shelter-457318-u6
  _CINAME: gke-image
  _VERSION: v1.0

options:
  logging: CLOUD_LOGGING_ONLY